metadata.format.version = "1.1"

[versions]

paper = "1.21.8-R0.1-SNAPSHOT"
sponge = "14.0.0"

blossom = "1.3.1"
shadow = "9.1.0"
runtask = "2.3.1"

miniplaceholders = "3.0.0-SNAPSHOT"
adventure = "4.24.0"

[libraries]

paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
sponge = { module = "org.spongepowered:spongeapi", version.ref = "sponge" }
miniplaceholders = { group = "io.github.miniplaceholders", name = "miniplaceholders-api", version.ref = "miniplaceholders" }

adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runtask" }
runpaper = { id = "xyz.jpenilla.run-velocity", version.ref = "runtask" }
