name: MiniPlaceholders-ItemDisplay-Expansion
version: '${version}'
author: 4drian3d
main: io.github.miniplaceholders.expansion.itemdisplay.paper.PaperPlugin
api-version: '1.19'
folia-supported: true
dependencies:
  server:
    MiniPlaceholders:
      required: true