name: Example-Expansion
version: '${version}'
author: 4drian3d
main: io.github.miniplaceholders.expansion.example.paper.PaperPlugin
api-version: '1.19'
folia-supported: true
dependencies:
  - name: MiniPlaceholders
    required: true
  # Add some plugin dependency
  #- name: spark
  #  required: true